CLI: fix traceback when -p is used with unsupported value
CLI: fix traceback when -p is used with unsupported value
$ tuna -t 4364 -p fif
Traceback (most recent call last):
  File "/usr/bin/tuna", line 647, in <module>
    main()
  File "/usr/bin/tuna", line 531, in main
    tuna.threads_set_priority(thread_list, a, affect_children)
  File "/usr/lib/python2.7/site-packages/tuna/tuna.py", line 502, in threads_set_priority
    rtprio = int(parms[0])
ValueError: invalid literal for int() with base 10: 'fif'

Signed-off-by: Petr Oros <poros@redhat.com>
Tested-by: Jiri Kastner <jkastner@redhat.com>
Signed-off-by: Jiri Kastner <jkastner@redhat.com>