cmdline: Always set irq_list_numbers to [] in ps_show_thread
So that when we don't pass a irq_list, it doesn't explodes later on:

[root@doppio tuna]# tuna -t 1,2 -P
                      thread       ctxt_switches
    pid SCHED_ rtpri affinity voluntary nonvoluntary             cmd
Traceback (most recent call last):
  File "./tuna-cmd.py", line 342, in <module>
    main()
  File "./tuna-cmd.py", line 272, in main
    kthreads, affect_children)
  File "./tuna-cmd.py", line 198, in do_ps
    has_ctxt_switch_info)
  File "./tuna-cmd.py", line 162, in ps_show
    if irq_list_numbers:
UnboundLocalError: local variable 'irq_list_numbers' referenced before
assignment
[root@doppio tuna]#

Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>