procview gui: Load perf globally
Used to work in previous python versions, but since at least 2.6.5 doing
the import in one method and then trying to use perf.something on
another doesn't work:

  File "/home/acme/git/tuna/tuna/gui/procview.py", line 317, in perf_init
    self.cpu_map = perf.cpu_map()
NameError: global name 'perf' is not defined

Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>