tuna: Present more graceful failure mode when machine can't start gui
Before:

[acme@emilia tuna]$ tuna
Traceback (most recent call last):
  File "./tuna-cmd.py", line 501, in ?
    main()
  File "./tuna-cmd.py", line 488, in main
    from tuna import tuna_gui
  File "/home/acme/git/tuna/tuna/tuna_gui.py", line 7, in ?
    import gtk, gobject, os, procfs, sys
  File "/usr/lib64/python2.4/site-packages/gtk-2.0/gtk/__init__.py", line 76, in ?
    _init()
  File "/usr/lib64/python2.4/site-packages/gtk-2.0/gtk/__init__.py", line 64, in _init
    _gtk.init_check()
RuntimeError: could not open display

After:

[acme@emilia tuna]$ tuna
tuna: machine needs to be authorized via xhost or ssh -X?

Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>